### ISSUE TITLE
configure coredump.conf 

### ISSUE THREAD

**Issue by tjungblu** [IBM/core-dump-handler#69]
Hey @No9,

sorry to annoy you again - another day, another requirement :)
Apparently there are coredumps that can be above 2G and there is a limit in systemd coredump.conf that needs to be configurable.

Specifically they need to set the following in `/etc/systemd/coredump.conf`:
```
ProcessSizeMax=2G
ExternalSizeMax=2G
```

Here's a MAN page for all the respective configuration values:
https://www.systutorials.com/docs/linux/man/5-coredump/

What do you think about adding a small config map that contains such values, and on pod start will write those into the conf file.

---

Looking a bit into this KCS article, for RHEL 7/8 I actually see we would need to restart a daemon:
https://access.redhat.com/solutions/649193

@travier apologies to pull you in here again, is there anything specific we need to pay attention to on CoreOS for those settings? I'm also happy to update the KCS article with information for it.

Cheers,
Thomas

**Comment by travier** [comment]
For RHCOS, I recommend dropping a file with the required configuration in the `.d` folder (`/etc/systemd/coredump.conf.d/*.conf`) via a MachineConfig instead of overriding the default configuration file (but that should also work).

I don't remember exactly which version introduced this support in systemd / RHEL 8 thus I would recommend verifying that this works too.

See https://man7.org/linux/man-pages/man5/coredump.conf.5.html

The sysctl configuration option can be set the same way via a MachineConfig. Configuration changes made via a MachineConfig will trigger a reboot thus no need to restart daemons.

**Comment by No9** [comment]
Hey @tjungblu - No problem hearing about use cases. It's what we love :) 
Not sure about the requirement though. 
From what I can tell from the [docs](https://man7.org/linux/man-pages/man8/systemd-coredump.8.html) (See `Configuration` section) systemd doesn't modify the capture of the core in the kernel it provides `systemd-coredump` to be piped into.
As we are providing our own capture service `core-dump-composer` we shouldn't need to configure systemd. 

That said I'm not a systemd expert so if I have missed something I'm happy to be corrected.

If I am correct then this is a useful note to capture as part of the systemd support that opened in https://github.com/IBM/core-dump-handler/issues/45 

_Aside note: systemd-coredump performs some namespace resolution that could be useful for better process information capture 
https://github.com/systemd/systemd/blob/main/src/coredump/coredump.c#L654_

**Comment by tjungblu** [comment]
right, that makes sense, let me divert back to the customer and their solution architect. 

Also thanks @travier, I passed the MCO solution back to them already.

**Comment by tjungblu** [comment]
Let's close this here for now, I need to file another issue for a related issue :)
